[build]
  publish = "."

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=600"

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


